language: node_js
node_js:
  - "8"
jobs:
  include:
    - stage: lint
      script: "npm run lint"
    - stage: install_master
      script: "npm i -g @vue/cli"
      script: "vue create --preset . preset-demo --bare && npm run build"